# Generated by Django 4.2.22 on 2025-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
