# Generated by Django 4.2.22 on 2025-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="banner",
            field=models.ImageField(
                blank=True, default="default-image.jpg", upload_to=""
            ),
        ),
    ]
